const usaStates = [
  {label: "Alabama", value: 50 },
  {label: "Alaska", value: 1 },
  {label: "Arizona", value: 2 },
  {label: "Arkansas", value: 3},
  {label: "California", value: 4},
  {label: "Colorado", value: 5},
  {label: "Connecticut", value: 6},
  {label: "Delaware", value: 7},
  {label: "Florida", value: 8},
  {label: "Georgia", value: 9},
  {label: "Hawaii", value: 10},
  {label: "Idaho", value: 11},
  {label: "Illinois", value: 12},
  {label: "Indiana", value: 13},
  {label: "Iowa", value: 14},
  {label: "Kansas", value: 15},
  {label: "Kentucky", value: 16},
  {label: "Louisiana", value: 17},
  {label: "Maine", value: 18},
  {label: "Maryland", value: 19},
  {label: "Massachusetts", value: 20},
  {label: "Michigan", value: 21},
  {label: "Minnesota", value: 22},
  {label: "Mississippi", value: 23},
  {label: "Missouri", value: 24},
  {label: "Montana", value: 25},
  {label: "Nebraska", value: 26},
  {label: "Nevada", value: 27},
  {label: "New Hampshire", value: 28},
  {label: "New Jersey", value: 29},
  {label: "New Mexico", value: 30},
  {label: "New York", value: 31},
  {label: "North Carolina", value: 32},
  {label: "North Dakota", value: 33},
  {label: "Ohio", value: 34},
  {label: "Oklahoma", value: 35},
  {label: "Oregon", value: 36},
  {label: "Pennsylvania", value: 37},
  {label: "Rhode Island", value: 38},
  {label: "South Carolina", value: 39},
  {label: "South Dakota", value: 40},
  {label: "Tennessee", value: 41},
  {label: "Texas", value: 42},
  {label:"Utah", value: 43},
  {label: "Vermont", value: 44},
  {label: "Virginia", value: 45},
  {label: "Washington", value: 46},
  {label: "West Virginia", value: 47},
  {label: "Wisconsin", value: 48},
{label: "Wyoming", value: 49}
]



export default usaStates;
